[display]
output_display = 0
frameless = false
transperent = false

[launcher]
enabled = true
icon_size = 64

[volumecontrol]
enabled = true

[powermonitor]
enabled = true
refresh_ms = 500
voltage_sensor = "/sys/class/hwmon/hwmon0/in0_input"
current_sensor = "/sys/class/hwmon/hwmon0/power1_cap"

[clock]
enabled = true
refresh_ms = 500
time_format = "%H:%M<sup><u>%S</u></sup>"
clock_color = "rgba(255, 255, 255, 255)"

[intervals]
sys_proc_refresh_ms = 60000
statusbar_msg_time_ms = 3000

[systemload]
enabled = true
cpu_temp_sensor_path = "/sys/class/hwmon/hwmon1/temp1_input"
sensor_refresh_ms = 500
cpu_temp_refresh_ms = 2000

[networkload]
enabled = true
interface = "enp39s0"
graph_data_limit = 60
network_refresh_ms = 5000
net_interval_ms = 200

[weather]
enabled = true
fefresh_min = 10
url = "http://api.openweathermap.org/data/2.5/weather?units=metric&"
city = "Kyiv"
we_temperature_color = "rgba(220, 250, 255, 250)"
we_humidity_color = "rgba(220, 250, 255, 250)"
we_pressure_color = "rgba(220, 250, 255, 250)"
we_condition_color = "rgba(220, 250, 255, 250)"
we_wind_speed_color = "rgba(220, 250, 255, 250)"
we_wind_dir_color = "rgba(220, 250, 255, 250)"

[openai]
visible = false
model_engine = "text-davinci-003"

[powermon]
enabled = false
